
[terminal.shell]
program = "/bin/fish"
# args = ["-l"]

[font]
size = 7.0

[font.normal]
family = "JetBrainsMonoNL NFP"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
opacity = 0.8

[window.padding]
x = 12
y = 12

[terminal]
